In [137]:
import torch
from stochman import nnj

In [138]:
_batch_size = 1
_input_size = 4
_hidden_size = 3
_output_size = 2

input = torch.randn(_batch_size, _input_size)
input2 = torch.randn(_batch_size, _input_size)

In [139]:
model = nnj.Linear(_input_size, _output_size)

### test single input ###
output = model(input)

tmp = torch.ones(_batch_size, _output_size)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _output_size, _output_size)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = False)


### test double input ###
output = model(input)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _output_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _output_size, _output_size)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

In [140]:
model = nnj.Tanh()

### test single input ###
output = model(input)

tmp = torch.ones(_batch_size, _input_size)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = False)


### test double input ###
output = model(input)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _input_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

In [141]:
model = nnj.ReLU()

### test single input ###
output = model(input)

tmp = torch.ones(_batch_size, _input_size)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = False)


### test double input ###
output = model(input)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _input_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

In [142]:
model = nnj.L2Norm()

### test single input ###
output = model(input)

tmp = torch.ones(_batch_size, _input_size)
#GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
#GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = False)


### test double input ###
output = model(input)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _input_size) for _ in range(3)]
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

In [143]:
layers = [nnj.Linear(_input_size, _hidden_size),
          nnj.Tanh(),
          nnj.Linear(_hidden_size, _hidden_size),
          nnj.ReLU(),
          nnj.Linear(_hidden_size, _output_size),
          nnj.L2Norm()
          ]
                        
model = nnj.Sequential(layers,
                  add_hooks = True
)
'''
### test single input ###
output = model(input)

tmp = torch.ones(_batch_size, _output_size)
GGN = model._jacobian_sandwich(input, tmp, wrt = 'input', diag_inp = True, method = 'diagonal exact')
GGN = model._jacobian_sandwich(input, tmp, wrt = 'weight', diag_inp = True, method = 'diagonal exact')
GGN = model._jacobian_sandwich(input, tmp, wrt = 'input', diag_inp = True, method = 'diagonal approx')
GGN = model._jacobian_sandwich(input, tmp, wrt = 'weight', diag_inp = True, method = 'diagonal approx')

tmp = torch.ones(_batch_size, _output_size, _output_size)
GGN = model._jacobian_sandwich(input, tmp, wrt = 'input', diag_inp = False, method = 'diagonal exact')
GGN = model._jacobian_sandwich(input, tmp, wrt = 'weight', diag_inp = False, method = 'diagonal exact')
GGN = model._jacobian_sandwich(input, tmp, wrt = 'input', diag_inp = False, method = 'diagonal approx')
GGN = model._jacobian_sandwich(input, tmp, wrt = 'weight', diag_inp = False, method = 'diagonal approx')
'''

### test double input ###
output = model(input)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _output_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input, input2, tmps, wrt = 'input', diag_inp = True, method = 'diagonal exact')
GGN = model._jacobian_sandwich_multipoint(input, input2, tmps, wrt = 'weight', diag_inp = True, method = 'diagonal exact')

tmps = [torch.ones(_batch_size, _output_size, _output_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input, input2, tmps, wrt = 'input', diag_inp = False, method = 'diagonal exact')
GGN = model._jacobian_sandwich_multipoint(input, input2, tmps, wrt = 'weight', diag_inp = False, method = 'diagonal exact')

# Check correctness

Define the same Neural network on Jax

In [144]:
stoch_model = nnj.Sequential([
                              nnj.Tanh(),
                              nnj.Linear(_input_size, _hidden_size),
                              nnj.Tanh(),
                              #nnj.ReLU(),
                              nnj.L2Norm(),
                              nnj.Linear(_hidden_size, _output_size),
                              #nnj.L2Norm()
                              ],
                  add_hooks = True
)

first_linear_layer_index = 1
second_linear_layer_index = 4

In [145]:
from jax import numpy as jnp
import numpy as np

def Relu(x):
    return jnp.maximum(x, jnp.zeros_like(x)) # max(0,x)

def Tanh(x):
    return jnp.tanh(x)

def L2Norm(x):
    x = x.T / (jnp.linalg.norm(x, ord=2, axis=1) + 1e-6)
    return x.T

def LinearLayer(w, b, x, print_weights=False):
    w = w.reshape(len(b), -1)
    out = jnp.dot(x, w.T) + b
    if print_weights:
        print('\twi\n\t',w)
        print('\tbi\n\t',b)
    return out

def jax_model(weights, x, print_weights=False):
    x = Tanh(x)
    w1 = weights[ : _input_size*_hidden_size]
    b1 = weights[_input_size*_hidden_size : _input_size*_hidden_size + _hidden_size]
    x = LinearLayer(w1, b1, x, print_weights=print_weights)
    x = Tanh(x)
    #x = Relu(x)
    x = L2Norm(x)
    w2 = weights[_input_size*_hidden_size + _hidden_size : _input_size*_hidden_size + _hidden_size + _hidden_size*_output_size]
    b2 = weights[_input_size*_hidden_size + _hidden_size + _hidden_size*_output_size : ]
    x = LinearLayer(w2, b2, x, print_weights=print_weights)
    #x = L2Norm(x)
    return x

_weights_size = _input_size*_hidden_size + _hidden_size + _hidden_size*_output_size + _output_size
        

In [146]:
stoch_input = torch.randn(_batch_size, _input_size)
print('Input:',stoch_input)
stoch_output = stoch_model.forward(stoch_input)

# set weights and input to be equal
print('Weights in stoch model:')
print('\tw1\n\t',stoch_model._modules_list[first_linear_layer_index].weight.detach().numpy())
print('\tb1\n\t',stoch_model._modules_list[first_linear_layer_index].bias.detach().numpy())
print('\tw2\n\t',stoch_model._modules_list[second_linear_layer_index].weight.detach().numpy())
print('\tb2\n\t',stoch_model._modules_list[second_linear_layer_index].bias.detach().numpy())


weights = []
for row in stoch_model._modules_list[first_linear_layer_index].weight.detach().numpy():
    weights = np.concatenate((weights, row))
weights= np.concatenate((weights, stoch_model._modules_list[first_linear_layer_index].bias.detach().numpy()))
for row in stoch_model._modules_list[second_linear_layer_index].weight.detach().numpy():
    weights = np.concatenate((weights, row))
weights = np.concatenate((weights, stoch_model._modules_list[second_linear_layer_index].bias.detach().numpy()))
weights = jnp.array(weights)
#print(_weights_size, len(weights))


jax_input = jnp.array(stoch_input.numpy())
jax_output = jax_model(weights, jax_input, print_weights=False)



print('Output stoch: \n', stoch_output)
print('Output jax: \n', jax_output)
#print('norms \n',jnp.linalg.norm(jax_output, ord=2, axis=1))

#print(np.array(jax_output) - stoch_output.detach().numpy())
#print(np.array(jax_output) == stoch_output.detach().numpy())
difference = np.array(jax_output) - stoch_output.detach().numpy()
print(np.max(abs(difference)))
assert (abs(difference) < 1e-6).all()
print('\n\nOutputs of stock and jax models are the same!')

Input: tensor([[-0.5130,  0.0337,  0.1497,  1.8129]])
Weights in stoch model:
	w1
	 [[-0.3820095   0.23412985  0.3846798   0.13565433]
 [-0.15018326 -0.22877079  0.23007387  0.37211066]
 [ 0.02995759  0.02596051 -0.15592879 -0.25911897]]
	b1
	 [ 0.12189823 -0.25463825 -0.46471483]
	w2
	 [[-0.4693359   0.3852045   0.4148506 ]
 [ 0.28866425  0.38507387  0.31575844]]
	b2
	 [ 0.09552045 -0.03102111]
Output stoch: 
 tensor([[-0.4056, -0.0225]], grad_fn=<AddmmBackward0>)
Output jax: 
 [[-0.40562892 -0.02246433]]
5.9604645e-08


Outputs of stock and jax models are the same!


# Check wrt the weights

Check vector-jacobian product

In [147]:
from jax import vjp

jax_output_by_vjp, vjp_fun = vjp(lambda w: jax_model(w, jax_input), weights)
# check if I'm actually understanding what jax.vjp is doing
assert (jax_output == jax_output_by_vjp).all()


e_0 = jnp.zeros((_batch_size, _output_size))
e_0 = e_0.at[0,0].set(1)
v_0_jax = vjp_fun(e_0)

e_0 = torch.zeros((_batch_size, _output_size))
e_0[0,0] = 1
v_0_stoch = stoch_model._vjp(e_0, stoch_input, wrt='weight')

print(e_0)
print('jax\t',np.array(v_0_jax))
print('stoch\t',v_0_stoch.detach().numpy())

for i in range(_output_size):
    e_i = jnp.zeros((_batch_size, _output_size))
    e_i = e_i.at[0,i].set(1)
    v_i_jax = vjp_fun(e_i)

    e_i = torch.zeros((_batch_size, _output_size))
    e_i[0,i] = 1
    v_i_stoch = stoch_model._vjp(e_i, stoch_input, wrt='weight')

    difference = np.array(v_i_jax) - v_i_stoch.detach().numpy()
    #print(np.array(v_i_jax) - v_i_stoch.detach().numpy())
    print('Max difference',np.max(abs(difference)), 'at index', np.argmax(abs(difference)))
    assert (abs(difference) < 1e-5).all()

print('\n\nVector-Jacobian products are the same for every base elements!')

tensor([[1., 0.]])
jax	 [[ 8.5077271e-02 -6.0604098e-03 -2.6760582e-02 -1.7078477e-01
  -2.8524080e-01  2.0318894e-02  8.9720897e-02  5.7259458e-01
  -7.3390719e-03  5.2279275e-04  2.3084641e-03  1.4732510e-02
  -1.8012941e-01  6.0392457e-01  1.5538611e-02  5.6971139e-01
   2.3974240e-01 -7.8609794e-01  0.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00]]
stoch	 [[ 8.5077435e-02 -6.0604224e-03 -2.6760638e-02 -1.7078510e-01
  -2.8524074e-01  2.0318894e-02  8.9720897e-02  5.7259446e-01
  -7.3392224e-03  5.2280357e-04  2.3085119e-03  1.4732812e-02
  -1.8012977e-01  6.0392451e-01  1.5538931e-02  5.6971139e-01
   2.3974240e-01 -7.8609800e-01  0.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00  0.0000000e+00]]
Max difference 3.5762787e-07 at index 12
Max difference 5.9604645e-08 at index 3


Vector-Jacobian products are the same for every base elements!


Check sandwich product

In [148]:
# tmp is the identity matrix, for each batch element
identity = []
for i in range(_output_size):
    e_i = jnp.zeros((_batch_size, _output_size))
    for b in range(_batch_size):
        e_i = e_i.at[b,i].set(1)
    identity.append(e_i)

rows_of_J_by_jax = []
for e_i in identity:
    v_i = vjp_fun(e_i)
    rows_of_J_by_jax.append(v_i[0])
print(len(v_i), v_i[0].shape)

rows_of_J_by_jax = np.array(rows_of_J_by_jax)
print(rows_of_J_by_jax.shape)

GGN_by_jax = jnp.einsum("ji,jk->ik", rows_of_J_by_jax, rows_of_J_by_jax)
print(GGN_by_jax.shape)

GGN_diagonal_by_jax = []
for w in range(_weights_size):
    GGN_diagonal_by_jax.append(GGN_by_jax[w][w])
GGN_diagonal_by_jax = jnp.array(GGN_diagonal_by_jax)
print(GGN_diagonal_by_jax.shape)


1 (23,)
(2, 23)
(23, 23)
(23,)


Do the same with stoch

In [149]:
# tmp is the identity matrix, for each batch element
identity = []
for i in range(_output_size):
    e_i = torch.zeros((_batch_size, _output_size))
    for b in range(_batch_size):
        e_i[b,i] = 1
    identity.append(e_i)

rows_of_J_by_stoch = []
for e_i in identity:
    v_i_stoch = stoch_model._vjp(e_i, stoch_input, wrt='weight')
    rows_of_J_by_stoch.append(v_i_stoch.detach().numpy()[0])
print(len(v_i_stoch), v_i_stoch[0].shape)

rows_of_J_by_stoch = np.array(rows_of_J_by_stoch)
print(rows_of_J_by_stoch.shape)

GGN_by_stoch_slow = np.einsum("ji,jk->ik", rows_of_J_by_stoch, rows_of_J_by_stoch)
print(GGN_by_stoch_slow.shape)

GGN_diagonal_by_stoch_slow = []
for w in range(_weights_size):
    GGN_diagonal_by_stoch_slow.append(GGN_by_stoch_slow[w][w])
GGN_diagonal_by_stoch_slow = jnp.array(GGN_diagonal_by_stoch_slow)
print(GGN_diagonal_by_stoch_slow.shape)


1 torch.Size([23])
(2, 23)
(23, 23)
(23,)


In [150]:
difference = rows_of_J_by_jax - rows_of_J_by_stoch
print(np.max(abs(difference)), 'at', np.argmax(abs(difference)))

assert np.max(abs(difference)) < 1e-5
print('Jacobians computed by row are the same')

3.5762787e-07 at 12
Jacobians computed by row are the same


In [151]:
difference = GGN_by_jax - GGN_by_stoch_slow
print(np.max(abs(difference)), 'at', np.argmax(abs(difference)))

assert np.max(abs(difference)) < 1e-5
print('Generalized Gauss Netowns (computed by row) are the same')

3.5762787e-07 at 297
Generalized Gauss Netowns (computed by row) are the same


In [152]:
identity_diagonal = torch.ones(_batch_size, _output_size)
GGN_diagonal_by_stoch = stoch_model._jacobian_sandwich(stoch_input,
                                                       identity_diagonal, 
                                                       wrt = 'weight', 
                                                       diag_inp = True, 
                                                       method = 'diagonal exact')

identity = torch.zeros(_batch_size, _output_size, _output_size)
for i in range(_output_size):
    for b in range(_batch_size):
        identity[b][i][i] = 1
GGN_diagonal_by_stoch2 = stoch_model._jacobian_sandwich(stoch_input,
                                                       identity, 
                                                       wrt = 'weight', 
                                                       diag_inp = False, 
                                                       method = 'diagonal exact')

In [153]:
print('stock\n',np.array(GGN_diagonal_by_stoch[0].detach()))
print('stoch slow\n',GGN_diagonal_by_stoch_slow)
print('jax\n',np.array(GGN_diagonal_by_jax))
print('diff\n',np.array(GGN_diagonal_by_stoch[0].detach()) - np.array(GGN_diagonal_by_jax))

stock
 [2.44889967e-02 1.24264770e-04 2.42289808e-03 9.86829698e-02
 1.28101870e-01 6.50028640e-04 1.26741715e-02 5.16210318e-01
 1.28803430e-02 6.53588577e-05 1.27435836e-03 5.19037396e-02
 1.09777465e-01 5.74245572e-01 5.77390492e-02 3.24571073e-01
 5.74764162e-02 6.17950082e-01 3.24571073e-01 5.74764162e-02
 6.17950082e-01 1.00000000e+00 1.00000000e+00]
stoch slow
 [2.44889986e-02 1.24264770e-04 2.42289784e-03 9.86829698e-02
 1.28101856e-01 6.50028582e-04 1.26741715e-02 5.16210258e-01
 1.28803430e-02 6.53588504e-05 1.27435836e-03 5.19037321e-02
 1.09777465e-01 5.74245572e-01 5.77390492e-02 3.24571073e-01
 5.74764162e-02 6.17950082e-01 3.24571073e-01 5.74764162e-02
 6.17950082e-01 1.00000000e+00 1.00000000e+00]
jax
 [2.4488963e-02 1.2426457e-04 2.4228939e-03 9.8682828e-02 1.2810189e-01
 6.5002847e-04 1.2674169e-02 5.1621038e-01 1.2880343e-02 6.5358829e-05
 1.2743579e-03 5.1903732e-02 1.0977730e-01 5.7424557e-01 5.7739038e-02
 3.2457107e-01 5.7476416e-02 6.1794996e-01 3.2457107e-01 5.

In [154]:
difference = np.array(GGN_diagonal_by_stoch[0].detach()) - np.array(GGN_diagonal_by_jax)
print(np.max(abs(difference)))

assert np.max(abs(difference)) < 1e-5
print('Generalized Gauss Newtown are the same')

1.6391277e-07
Generalized Gauss Newtown are the same


# Check wrt the input

Check vector-jacobian product

In [155]:
jax_output_by_vjp, vjp_fun = vjp(lambda inp: jax_model(weights, inp), jax_input)
# check if the outputs are the same
assert (jax_output == jax_output_by_vjp).all()


e_0 = jnp.zeros((_batch_size, _output_size))
e_0 = e_0.at[0,0].set(1)
v_0_jax = vjp_fun(e_0)

e_0 = torch.zeros((_batch_size, _output_size))
e_0[0,0] = 1
v_0_stoch = stoch_model._vjp(e_0, stoch_input, wrt='input')

print(e_0)
print('jax\t',np.array(v_0_jax))
print('stoch\t',v_0_stoch.detach().numpy())

for i in range(_output_size):
    e_i = jnp.zeros((_batch_size, _output_size))
    e_i = e_i.at[0,i].set(1)
    v_i_jax = vjp_fun(e_i)

    e_i = torch.zeros((_batch_size, _output_size))
    e_i[0,i] = 1
    v_i_stoch = stoch_model._vjp(e_i, stoch_input, wrt='input')

    #print(np.array(v_i_jax) - v_i_stoch.detach().numpy())
    assert (np.array(v_i_jax) - v_i_stoch.detach().numpy() < 1e-5).all()

tensor([[1., 0.]])
jax	 [[[-0.01664377 -0.17972691  0.06574833  0.01983521]]]
stoch	 [[-0.01664365 -0.17972697  0.06574812  0.01983522]]


Check sandwich product

In [156]:
# tmp is the identity matrix, for each batch element
identity = []
for i in range(_output_size):
    e_i = jnp.zeros((_batch_size, _output_size))
    for b in range(_batch_size):
        e_i = e_i.at[b,i].set(1)
    identity.append(e_i)

rows_of_J_by_jax = []
for row in identity:
    v_i = vjp_fun(row)
    rows_of_J_by_jax.append(v_i[0][0])
print(len(v_i), v_i[0].shape)

rows_of_J_by_jax = np.array(rows_of_J_by_jax)
print(rows_of_J_by_jax.shape)

GGN_by_jax = np.einsum("ji,jk->ik", rows_of_J_by_jax, rows_of_J_by_jax)
print(GGN_by_jax.shape)

1 (1, 4)
(2, 4)
(4, 4)


Do the same with stoch

In [157]:
# tmp is the identity matrix, for each batch element
identity = []
for i in range(_output_size):
    e_i = torch.zeros((_batch_size, _output_size))
    for b in range(_batch_size):
        e_i[b,i] = 1
    identity.append(e_i)

rows_of_J_by_stoch = []
for e_i in identity:
    v_i_stoch = stoch_model._vjp(e_i, stoch_input, wrt='input')
    rows_of_J_by_stoch.append(v_i_stoch.detach().numpy()[0])
print(len(v_i_stoch), v_i_stoch[0].shape)

rows_of_J_by_stoch = np.array(rows_of_J_by_stoch)
print(rows_of_J_by_stoch.shape)

GGN_by_stoch_slow = np.einsum("ji,jk->ik", rows_of_J_by_stoch, rows_of_J_by_stoch)
print(GGN_by_stoch_slow.shape)

1 torch.Size([4])
(2, 4)
(4, 4)


In [158]:
difference = rows_of_J_by_jax - rows_of_J_by_stoch
print(np.max(abs(difference)), 'at', np.argmax(abs(difference)))

assert np.max(abs(difference)) < 1e-5
print('Jacobians computed by row are the same')

2.0861626e-07 at 2
Jacobians computed by row are the same


In [159]:
difference = GGN_by_jax - GGN_by_stoch_slow
print(np.max(abs(difference)), 'at', np.argmax(abs(difference)))

assert np.max(abs(difference)) < 1e-5
print('Generalized Gauss Netowns (computed by row) are the same')

3.1664968e-08 at 6
Generalized Gauss Netowns (computed by row) are the same


In [160]:
identity_diagonal = torch.ones(_batch_size, _output_size)
GGN_by_stoch = stoch_model._jacobian_sandwich(stoch_input,
                                            identity_diagonal, 
                                            wrt = 'input', 
                                            diag_inp = True, 
                                            method = 'diagonal exact')

In [161]:
print('stoch\n',np.array(GGN_by_stoch[0].detach()))
print('stoch slow \n',np.array(GGN_by_stoch_slow))
print('jax\n',np.array(GGN_by_jax))
print('diff\n',np.array(GGN_by_stoch[0].detach()) - np.array(GGN_by_jax))

#print('diff\n',np.array(GGN_by_stoch[0].detach()) == np.array(GGN_by_jax))
print('diff\n',abs(np.array(GGN_by_stoch[0].detach()) - np.array(GGN_by_jax)) < 1e-6)


#print('ratio\n',np.array(GGN_by_stoch[0].detach()) / np.array(GGN_by_jax))

stoch
 [[ 0.01727092  0.00733828 -0.0233907  -0.00225256]
 [ 0.00733828  0.03341372 -0.01752003 -0.00405667]
 [-0.0233907  -0.01752004  0.03357622  0.0038264 ]
 [-0.00225256 -0.00405667  0.0038264   0.00061091]]
stoch slow 
 [[ 0.01727092  0.00733828 -0.0233907  -0.00225256]
 [ 0.00733828  0.03341372 -0.01752004 -0.00405667]
 [-0.0233907  -0.01752004  0.03357621  0.0038264 ]
 [-0.00225256 -0.00405667  0.0038264   0.00061091]]
jax
 [[ 0.01727092  0.0073383  -0.0233907  -0.00225256]
 [ 0.0073383   0.0334137  -0.01752007 -0.00405667]
 [-0.0233907  -0.01752007  0.03357624  0.0038264 ]
 [-0.00225256 -0.00405667  0.0038264   0.00061091]]
diff
 [[ 3.7252903e-09 -1.8626451e-08  5.5879354e-09 -4.6566129e-10]
 [-2.0489097e-08  2.2351742e-08  3.3527613e-08 -2.7939677e-09]
 [ 5.5879354e-09  2.9802322e-08 -2.2351742e-08  2.3283064e-10]
 [-4.6566129e-10 -3.7252903e-09 -2.3283064e-10  8.7311491e-10]]
diff
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True 