In [22]:
import torch
from stochman import nnj

In [23]:
_batch_size = 2
_input_size = 3
_hidden_size = 2
_output_size = 1

input1 = torch.randn(_batch_size, _input_size)
input2 = torch.randn(_batch_size, _input_size)

In [25]:
model = nnj.Linear(_input_size, _output_size)

### test double input ###
output = model(input1)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _output_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _output_size, _output_size)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

In [26]:
model = nnj.Tanh()

### test double input ###
output = model(input1)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _input_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

In [27]:
model = nnj.ReLU()

### test double input ###
output = model(input1)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _input_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

In [28]:
model = nnj.L2Norm()

### test double input ###
output = model(input1)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _input_size) for _ in range(3)]
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input1, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

In [29]:
layers = [nnj.Linear(_input_size, _hidden_size),
          nnj.Tanh(),
          nnj.Linear(_hidden_size, _hidden_size),
          nnj.ReLU(),
          nnj.Linear(_hidden_size, _output_size),
          nnj.L2Norm()
          ]
                        
model = nnj.Sequential(layers,
                  add_hooks = True
)

### test double input ###
output = model(input1)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _output_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input1, input2, tmps, wrt = 'input', diag_inp = True, method = 'diagonal exact')
GGN = model._jacobian_sandwich_multipoint(input1, input2, tmps, wrt = 'weight', diag_inp = True, method = 'diagonal exact')

tmps = [torch.ones(_batch_size, _output_size, _output_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input1, input2, tmps, wrt = 'input', diag_inp = False, method = 'diagonal exact')
GGN = model._jacobian_sandwich_multipoint(input1, input2, tmps, wrt = 'weight', diag_inp = False, method = 'diagonal exact')

# Check correctness

Define the same Neural network on Jax

In [30]:
stoch_model = nnj.Sequential([
                              nnj.Tanh(),
                              nnj.Linear(_input_size, _hidden_size),
                              nnj.Tanh(),
                              #nnj.ReLU(),
                              nnj.L2Norm(),
                              nnj.Linear(_hidden_size, _output_size),
                              #nnj.L2Norm()
                              ],
                  add_hooks = True
)

first_linear_layer_index = 1
second_linear_layer_index = 4

In [31]:
from jax import numpy as jnp
import numpy as np

def Relu(x):
    return jnp.maximum(x, jnp.zeros_like(x)) # max(0,x)

def Tanh(x):
    return jnp.tanh(x)

def L2Norm(x):
    x = x.T / (jnp.linalg.norm(x, ord=2, axis=1) + 1e-6)
    return x.T

def LinearLayer(w, b, x, print_weights=False):
    w = w.reshape(len(b), -1)
    out = jnp.dot(x, w.T) + b
    if print_weights:
        print('\twi\n\t',w)
        print('\tbi\n\t',b)
    return out

def jax_model(weights, x, print_weights=False):
    x = Tanh(x)
    w1 = weights[ : _input_size*_hidden_size]
    b1 = weights[_input_size*_hidden_size : _input_size*_hidden_size + _hidden_size]
    x = LinearLayer(w1, b1, x, print_weights=print_weights)
    x = Tanh(x)
    #x = Relu(x)
    x = L2Norm(x)
    w2 = weights[_input_size*_hidden_size + _hidden_size : _input_size*_hidden_size + _hidden_size + _hidden_size*_output_size]
    b2 = weights[_input_size*_hidden_size + _hidden_size + _hidden_size*_output_size : ]
    x = LinearLayer(w2, b2, x, print_weights=print_weights)
    #x = L2Norm(x)
    return x

_weights_size = _input_size*_hidden_size + _hidden_size + _hidden_size*_output_size + _output_size
        

In [32]:
stoch_input1 = torch.randn(_batch_size, _input_size)
stoch_input2 = torch.randn(_batch_size, _input_size)
print('Input1:',stoch_input1)
print('Input2:',stoch_input2)
stoch_output1 = stoch_model.forward(stoch_input1)
stoch_output2 = stoch_model.forward(stoch_input2)

# set weights and input to be equal
print('Weights in stoch model:')
print('\tw1\n\t',stoch_model._modules_list[first_linear_layer_index].weight.detach().numpy())
print('\tb1\n\t',stoch_model._modules_list[first_linear_layer_index].bias.detach().numpy())
print('\tw2\n\t',stoch_model._modules_list[second_linear_layer_index].weight.detach().numpy())
print('\tb2\n\t',stoch_model._modules_list[second_linear_layer_index].bias.detach().numpy())


weights = []
for row in stoch_model._modules_list[first_linear_layer_index].weight.detach().numpy():
    weights = np.concatenate((weights, row))
weights= np.concatenate((weights, stoch_model._modules_list[first_linear_layer_index].bias.detach().numpy()))
for row in stoch_model._modules_list[second_linear_layer_index].weight.detach().numpy():
    weights = np.concatenate((weights, row))
weights = np.concatenate((weights, stoch_model._modules_list[second_linear_layer_index].bias.detach().numpy()))
weights = jnp.array(weights)
#print(_weights_size, len(weights))


jax_input1 = jnp.array(stoch_input1.numpy())
jax_input2 = jnp.array(stoch_input2.numpy())
#print('Weights in jax model:')
jax_output1 = jax_model(weights, jax_input1, print_weights=False)
jax_output2 = jax_model(weights, jax_input2, print_weights=False)



print('Output1: \n', jax_output1)
print('Output2: \n', jax_output2)
#print('norms \n',jnp.linalg.norm(jax_output, ord=2, axis=1))

#print(np.array(jax_output) - stoch_output.detach().numpy())
#print(np.array(jax_output) == stoch_output.detach().numpy())
difference1 = np.array(jax_output1) - stoch_output1.detach().numpy()
difference2 = np.array(jax_output2) - stoch_output2.detach().numpy()
print(np.max(abs(difference1)), np.max(abs(difference2)))
assert (abs(difference1) < 1e-6).all() and (abs(difference2) < 1e-6).all()
print('\n\nOutputs of stock and jax models are the same!')

Input1: tensor([[ 0.4592,  1.7532,  1.2572],
        [-0.2399, -0.1848,  0.6182]])
Input2: tensor([[-0.5009, -1.4418, -0.5515],
        [-0.2437, -2.9064,  1.1754]])
Weights in stoch model:
	w1
	 [[-0.26317582 -0.35932797 -0.520204  ]
 [-0.56792915  0.4255187   0.48647   ]]
	b1
	 [-0.1295054  -0.49002025]
	w2
	 [[ 0.50896794 -0.25101432]]
	b2
	 [0.6121177]
Output1: 
 [[0.07989365]
 [0.3009029 ]]
Output2: 
 [[1.1182475]
 [0.6633612]]
0.0 1.1920929e-07


Outputs of stock and jax models are the same!


# Check wrt the weights

Check vector-jacobian product

In [33]:
from jax import vjp

jax_output_by_vjp1, vjp_fun1 = vjp(lambda w: jax_model(w, jax_input1), weights)
jax_output_by_vjp2, vjp_fun2 = vjp(lambda w: jax_model(w, jax_input2), weights)
# check if I'm actually understanding what jax.vjp is doing
assert (jax_output1 == jax_output_by_vjp1).all()
assert (jax_output2 == jax_output_by_vjp2).all()

for i in range(_output_size):
    for vjp_fun,stoch_input in [(vjp_fun1, stoch_input1), (vjp_fun2, stoch_input2)]:
        e_i = jnp.zeros((_batch_size, _output_size))
        e_i = e_i.at[0,i].set(1)
        v_i_jax = vjp_fun(e_i)

        e_i = torch.zeros((_batch_size, _output_size))
        e_i[0,i] = 1
        v_i_stoch = stoch_model._vjp(e_i, stoch_input, wrt='weight')

        difference = np.array(v_i_jax) - v_i_stoch.detach().numpy()
        print(np.array(v_i_jax), v_i_stoch.detach().numpy())
        print('Max difference',np.max(abs(difference)), 'at index', np.argmax(abs(difference)))
        assert (abs(difference) < 1e-5).all()

print('\n\nVector-Jacobian products are the same for every base elements!')

[[-0.00457794 -0.01003927 -0.00906444 -0.10780229 -0.2364071  -0.2134516
  -0.01066033 -0.25103188 -0.9946227   0.10355183  1.        ]] [[-0.00457778 -0.01003893 -0.00906414 -0.10780233 -0.23640716 -0.21345164
  -0.01065997 -0.25103194 -0.9946227   0.10355193  1.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.         -0.         -0.          0.        ]]
Max difference 1.0 at index 21


AssertionError: 

Check sandwich product

In [ ]:
# tmp is the identity matrix, for each batch element
identity = []
for i in range(_output_size):
    e_i = jnp.zeros((_batch_size, _output_size))
    for b in range(_batch_size):
        e_i = e_i.at[b,i].set(1)
    identity.append(e_i)

rows_of_J1_by_jax = []
rows_of_J2_by_jax = []
for vjp_fun,rows_of_J_by_jax in [(vjp_fun1, rows_of_J1_by_jax), (vjp_fun2, rows_of_J2_by_jax)]:
    for e_i in identity:
        v_i = vjp_fun(e_i)
        rows_of_J_by_jax.append(v_i[0])
    rows_of_J_by_jax = np.array(rows_of_J_by_jax)

JJ11_by_jax = jnp.einsum("ji,jk->ik", rows_of_J1_by_jax, rows_of_J1_by_jax)
JJ12_by_jax = jnp.einsum("ji,jk->ik", rows_of_J1_by_jax, rows_of_J2_by_jax)
JJ22_by_jax = jnp.einsum("ji,jk->ik", rows_of_J2_by_jax, rows_of_J2_by_jax)
GGN_by_jax = JJ11_by_jax + JJ22_by_jax - JJ12_by_jax - JJ12_by_jax.T
print(GGN_by_jax.shape)

GGN_diagonal_by_jax = []
for w in range(_weights_size):
    GGN_diagonal_by_jax.append(GGN_by_jax[w][w])
GGN_diagonal_by_jax = jnp.array(GGN_diagonal_by_jax)
print(GGN_diagonal_by_jax.shape)


(11, 11)
(11,)


Do the same with stoch

In [ ]:
# tmp is the identity matrix, for each batch element
identity = []
for i in range(_output_size):
    e_i = torch.zeros((_batch_size, _output_size))
    for b in range(_batch_size):
        e_i[b,i] = 1
    identity.append(e_i)

rows_of_J1_by_stoch = []
rows_of_J2_by_stoch = []
for stoch_input,rows_of_J_by_stoch in [(stoch_input1, rows_of_J1_by_stoch), (stoch_input2, rows_of_J2_by_stoch)]:
    for e_i in identity:
        v_i_stoch = stoch_model._vjp(e_i, stoch_input, wrt='weight')
        rows_of_J_by_stoch.append(v_i_stoch.detach().numpy()[0])
    rows_of_J_by_stoch = np.array(rows_of_J_by_stoch)

JJ11_by_stoch = np.einsum("ji,jk->ik", rows_of_J1_by_stoch, rows_of_J1_by_stoch)
JJ12_by_stoch = np.einsum("ji,jk->ik", rows_of_J1_by_stoch, rows_of_J2_by_stoch)
JJ22_by_stoch = np.einsum("ji,jk->ik", rows_of_J2_by_stoch, rows_of_J2_by_stoch)
GGN_by_stoch_slow = JJ11_by_stoch + JJ22_by_stoch - JJ12_by_stoch - JJ12_by_stoch.T
print(GGN_by_stoch_slow.shape)

GGN_diagonal_by_stoch_slow = []
for w in range(_weights_size):
    GGN_diagonal_by_stoch_slow.append(GGN_by_stoch_slow[w][w])
GGN_diagonal_by_stoch_slow = jnp.array(GGN_diagonal_by_stoch_slow)
print(GGN_diagonal_by_stoch_slow.shape)


(11, 11)
(11,)


In [ ]:
difference = rows_of_J_by_jax - rows_of_J_by_stoch
print(np.max(abs(difference)), 'at', np.argmax(abs(difference)))

assert np.max(abs(difference)) < 1e-5
print('Jacobians computed by row are the same')

5.9604645e-08 at 9
Jacobians computed by row are the same


In [ ]:
difference = GGN_by_jax - GGN_by_stoch_slow
print(np.max(abs(difference)), 'at', np.argmax(abs(difference)))

assert np.max(abs(difference)) < 1e-5
print('Generalized Gauss Netowns (computed by row) are the same')

1.1920929e-07 at 108
Generalized Gauss Netowns (computed by row) are the same


In [ ]:
difference = JJ12_by_stoch - JJ12_by_stoch.T
print('How much non symmetric is the cross term ->', np.max(abs(difference)))

How much non symmetric is the cross term -> 0.31406224


In [ ]:
identity_diagonals = tuple(torch.ones(_batch_size, _output_size) for _ in range(3))
GGN_diagonal_by_stoch = stoch_model._jacobian_sandwich_multipoint(stoch_input1,
                                                                  stoch_input2,
                                                                  identity_diagonals, 
                                                                  wrt = 'weight', 
                                                                  diag_inp = True, 
                                                                  method = 'diagonal exact')

identities = tuple(torch.zeros(_batch_size, _output_size, _output_size) for _ in range(3))
for s in range(3):
    for i in range(_output_size):
        for b in range(_batch_size):
            identities[s][b][i][i] = 1
GGN_diagonal_by_stoch2 = stoch_model._jacobian_sandwich_multipoint(stoch_input1,
                                                                   stoch_input2,
                                                                   identities, 
                                                                   wrt = 'weight', 
                                                                   diag_inp = False, 
                                                                   method = 'diagonal exact')

In [ ]:
print('stock\n',np.array(GGN_diagonal_by_stoch[0].detach()))
print('stoch slow\n',GGN_diagonal_by_stoch_slow)
print('jax\n',np.array(GGN_diagonal_by_jax))
print('diff\n',np.array(GGN_diagonal_by_stoch[0].detach()) - np.array(GGN_diagonal_by_jax))

stock
 [0.00260411 0.0219567  0.06252824 0.00067645 0.00070043 0.04717448
 0.0289547  0.00203911 0.05857497 0.04262051 0.        ]
stoch slow
 [0.00260411 0.0219567  0.06252824 0.00067645 0.00070043 0.04717447
 0.02895471 0.00203911 0.05857497 0.04262054 0.        ]
jax
 [0.00260411 0.02195673 0.06252827 0.00067646 0.00070043 0.04717442
 0.02895473 0.00203912 0.05857497 0.04262042 0.        ]
diff
 [-3.2596290e-09 -2.6077032e-08 -2.9802322e-08 -3.7252903e-09
 -3.7252903e-09  5.5879354e-08 -2.9802322e-08 -1.3038516e-08
  0.0000000e+00  8.9406967e-08  0.0000000e+00]


In [ ]:
difference = np.array(GGN_diagonal_by_stoch[0].detach()) - np.array(GGN_diagonal_by_jax)
print(np.max(abs(difference)))

assert np.max(abs(difference)) < 1e-5
print('Generalized Gauss Newtown are the same')

8.940697e-08
Generalized Gauss Newtown are the same


# Check wrt the input

Check vector-jacobian product

In [ ]:
jax_output_by_vjp, vjp_fun = vjp(lambda inp: jax_model(weights, inp), jax_input)
# check if the outputs are the same
assert (jax_output == jax_output_by_vjp).all()


e_0 = jnp.zeros((_batch_size, _output_size))
e_0 = e_0.at[0,0].set(1)
v_0_jax = vjp_fun(e_0)

e_0 = torch.zeros((_batch_size, _output_size))
e_0[0,0] = 1
v_0_stoch = stoch_model._vjp(e_0, stoch_input, wrt='input')

print(e_0)
print('jax\t',np.array(v_0_jax))
print('stoch\t',v_0_stoch.detach().numpy())

for i in range(_output_size):
    e_i = jnp.zeros((_batch_size, _output_size))
    e_i = e_i.at[0,i].set(1)
    v_i_jax = vjp_fun(e_i)

    e_i = torch.zeros((_batch_size, _output_size))
    e_i[0,i] = 1
    v_i_stoch = stoch_model._vjp(e_i, stoch_input, wrt='input')

    #print(np.array(v_i_jax) - v_i_stoch.detach().numpy())
    assert (np.array(v_i_jax) - v_i_stoch.detach().numpy() < 1e-5).all()

NameError: name 'jax_input' is not defined

Check sandwich product

In [ ]:
# tmp is the identity matrix, for each batch element
identity = []
for i in range(_output_size):
    e_i = jnp.zeros((_batch_size, _output_size))
    for b in range(_batch_size):
        e_i = e_i.at[b,i].set(1)
    identity.append(e_i)

rows_of_J_by_jax = []
for row in identity:
    v_i = vjp_fun(row)
    rows_of_J_by_jax.append(v_i[0][0])
print(len(v_i), v_i[0].shape)

rows_of_J_by_jax = np.array(rows_of_J_by_jax)
print(rows_of_J_by_jax.shape)

GGN_by_jax = np.einsum("ji,jk->ik", rows_of_J_by_jax, rows_of_J_by_jax)
print(GGN_by_jax.shape)

1 (1, 4)
(2, 4)
(4, 4)


Do the same with stoch

In [ ]:
# tmp is the identity matrix, for each batch element
identity = []
for i in range(_output_size):
    e_i = torch.zeros((_batch_size, _output_size))
    for b in range(_batch_size):
        e_i[b,i] = 1
    identity.append(e_i)

rows_of_J_by_stoch = []
for e_i in identity:
    v_i_stoch = stoch_model._vjp(e_i, stoch_input, wrt='input')
    rows_of_J_by_stoch.append(v_i_stoch.detach().numpy()[0])
print(len(v_i_stoch), v_i_stoch[0].shape)

rows_of_J_by_stoch = np.array(rows_of_J_by_stoch)
print(rows_of_J_by_stoch.shape)

GGN_by_stoch_slow = np.einsum("ji,jk->ik", rows_of_J_by_stoch, rows_of_J_by_stoch)
print(GGN_by_stoch_slow.shape)

1 torch.Size([4])
(2, 4)
(4, 4)


In [ ]:
difference = rows_of_J_by_jax - rows_of_J_by_stoch
print(np.max(abs(difference)), 'at', np.argmax(abs(difference)))

assert np.max(abs(difference)) < 1e-5
print('Jacobians computed by row are the same')

5.364418e-07 at 1
Jacobians computed by row are the same


In [ ]:
difference = GGN_by_jax - GGN_by_stoch_slow
print(np.max(abs(difference)), 'at', np.argmax(abs(difference)))

assert np.max(abs(difference)) < 1e-5
print('Generalized Gauss Netowns (computed by row) are the same')

2.6775524e-08 at 5
Generalized Gauss Netowns (computed by row) are the same


In [ ]:
identity_diagonal = torch.ones(_batch_size, _output_size)
GGN_by_stoch = stoch_model._jacobian_sandwich(stoch_input,
                                            identity_diagonal, 
                                            wrt = 'input', 
                                            diag_inp = True, 
                                            method = 'diagonal exact')

In [ ]:
print('stoch\n',np.array(GGN_by_stoch[0].detach()))
print('stoch slow \n',np.array(GGN_by_stoch_slow))
print('jax\n',np.array(GGN_by_jax))
print('diff\n',np.array(GGN_by_stoch[0].detach()) - np.array(GGN_by_jax))

#print('diff\n',np.array(GGN_by_stoch[0].detach()) == np.array(GGN_by_jax))
print('diff\n',abs(np.array(GGN_by_stoch[0].detach()) - np.array(GGN_by_jax)) < 1e-6)


#print('ratio\n',np.array(GGN_by_stoch[0].detach()) / np.array(GGN_by_jax))

stoch
 [[ 0.03766713 -0.01087428  0.01152801 -0.00608769]
 [-0.01087428  0.00375755 -0.00417262  0.00174075]
 [ 0.01152801 -0.00417262  0.0046819  -0.00184027]
 [-0.00608769  0.00174075 -0.00184027  0.00098433]]
stoch slow 
 [[ 0.03766714 -0.01087427  0.011528   -0.00608769]
 [-0.01087427  0.00375755 -0.00417262  0.00174075]
 [ 0.011528   -0.00417262  0.0046819  -0.00184027]
 [-0.00608769  0.00174075 -0.00184027  0.00098433]]
jax
 [[ 0.03766712 -0.01087426  0.01152799 -0.00608768]
 [-0.01087426  0.00375752 -0.0041726   0.00174074]
 [ 0.01152799 -0.0041726   0.00468189 -0.00184027]
 [-0.00608768  0.00174074 -0.00184027  0.00098433]]
diff
 [[ 1.49011612e-08 -1.30385160e-08  1.86264515e-08 -1.21071935e-08]
 [-1.21071935e-08  3.09664756e-08 -2.37487257e-08  2.79396772e-09]
 [ 1.86264515e-08 -2.65426934e-08  1.25728548e-08 -4.07453626e-09]
 [-1.21071935e-08  3.37604433e-09 -4.07453626e-09  3.25962901e-09]]
diff
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True